version = 1

[approve]
auto_approve_usernames = [ "dependabot" ]

[merge]
automerge_dependencies.usernames = [ "dependabot" ]
require_automerge_label = false

[update]
ignored_usernames = [ "dependabot" ]
