trigger:
  branches:
    include: [ main ]
pr:
  branches:
    include: [ main ]

variables:
  Disable.Coverage.AutoGenerate: true
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - checkout: self
        displayName: Checkout source
        submodules: recursive

      - task: Cache@2
        displayName: Cache packages
        inputs:
          path: $(NUGET_PACKAGES)
          key: $(Agent.OS)|nuget|.config/dotnet-tools.json,**/packages.lock.json
          restoreKeys: $(Agent.OS)|nuget

      - bash: dotnet tool restore && dotnet cake --verbosity=verbose
        displayName: Cake build

      - task: PublishTestResults@2
        displayName: Tests report
        inputs:
          testRunner: VSTest
          testResultsFiles: "Artifacts/Tests/*/TestResults.trx"

      - task: PublishCodeCoverageResults@1
        displayName: Coverage report
        inputs:
          codeCoverageTool: Cobertura
          reportDirectory: Artifacts/Tests/Coverage
          summaryFileLocation: Artifacts/Tests/Coverage/Cobertura.xml
