trigger:
  branches:
    include: [ master ]
pr:
  branches:
    include: [ master ]

variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - checkout: self
        displayName: Checkout source
        submodules: true

      - task: Cache@2
        displayName: Cache packages
        inputs:
          path: $(NUGET_PACKAGES)
          key: $(Agent.OS)|nuget|.config/dotnet-tools.json,**/packages.lock.json
          restoreKeys: $(Agent.OS)|nuget

      - bash: dotnet tool restore && dotnet cake --verbosity=verbose
        displayName: Cake build

      - task: PublishTestResults@2
        displayName: Upload test artifacts
        inputs:
          testRunner: VSTest
          testResultsFiles: "Artifacts/Tests/*/*.trx"

      - task: PublishCodeCoverageResults@1
        displayName: Upload coverage artifacts
        inputs:
          codeCoverageTool: cobertura
          summaryFileLocation: "Artifacts/Tests/*/*/coverage.*.xml"
