trigger:
  branches:
    include:
      - "**"
    exclude:
      - "dependabot/**"
pr:
  branches:
    include:
      - master

variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

jobs:
  - job: Docker
    pool:
      vmImage: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - checkout: self
        displayName: Checkout source

      - task: Cache@2
        inputs:
          path: $(NUGET_PACKAGES)
          key: $(Agent.OS)|nuget|.config/dotnet-tools.json,**/packages.lock.json
          restoreKeys: $(Agent.OS)|nuget
        displayName: Cache packages

      - task: Docker@2
        inputs:
          command: login
          containerRegistry: DockerHub
        displayName: Docker login

      - bash: dotnet tool restore && dotnet cake --bootstrap && dotnet cake --verbosity=verbose --target=build
        displayName: Cake build

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "Artifacts/Tests/*/*.trx"
        displayName: Upload test artifacts

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: cobertura
          summaryFileLocation: "Artifacts/Tests/*/*/coverage.*.xml"
        displayName: Upload coverage artifacts
