trigger:
  - "**"
pr:
  - master

variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

jobs:
  - job: Docker
    pool:
      vmImage: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - checkout: self
        displayName: Checkout source

      - bash: touch "$HOME/.dotnet/$(dotnet --version).dotnetFirstUseSentinel"
        displayName: Touch dotnet

      - task: Cache@2
        inputs:
          path: $(NUGET_PACKAGES)
          key: $(Agent.OS)|nuget|**/packages.lock.json
          restoreKeys: $(Agent.OS)|nuget
        displayName: Cache packages

      - task: Docker@2
        inputs:
          command: login
          containerRegistry: DockerHub
        displayName: Docker login

      - bash: dotnet tool restore && dotnet cake --bootstrap && dotnet cake --verbosity=verbose --target=build --publish=true
        displayName: Cake build
