workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

variables:
  DOCKER_HOST: tcp://docker:2375
  GIT_DEPTH: 0
  GIT_SUBMODULE_STRATEGY: recursive
  NUGET_PACKAGES: $CI_PROJECT_DIR/.nuget/packages

services:
  - docker:dind

stages: [ build ]

docker:
  stage: build
  tags: [ shared, linux, docker ]
  image: dockfool/cake-docker:latest
  cache:
    paths: [ $NUGET_PACKAGES ]
    key:
      prefix: linux-nuget
      files: [ packages.lock.json ]
  script:
    - dotnet tool restore && dotnet cake --verbosity=verbose
    - dotnet tool install trx2junit --tool-path /usr/local/bin && trx2junit Artifacts/Tests/*/*.trx
  coverage: /\s*Line coverage:\s*(\d+(?:\.\d+)?)%/
  artifacts:
    reports:
      junit: Artifacts/Tests/*/*.xml
      cobertura: Artifacts/Tests/*/*/coverage.*.xml
