trigger:
- master

jobs:
- job: Docker
  pool:
    vmImage: ubuntu-16.04
  container: dockfool/cake-docker:latest
  steps:
  - task: Docker@2
    inputs:
      command: login
      containerRegistry: DockerHub
    displayName: Docker login

  - bash: cake --bootstrap && cake --verbosity=verbose --ispublisher=true
    displayName: Cake build
