trigger:
- master

variables:
- group: Cake

jobs:
- job: Docker
  pool:
    vmImage: ubuntu-16.04
  container:
    image: dockfool/cake-docker:1.0.1-pre.2
  steps:
  - task: Docker@1
    displayName: Docker login
    inputs:
      command: login
      containerRegistryType: Container Registry
      dockerRegistryEndpoint: DockerHub

  - bash: |
      set -ex
      sudo groupadd -g $(stat --format='%g' /var/run/docker.sock) docker
      sudo usermod -a -G docker $(whoami)
    displayName: Docker socket

  - bash: |
      set -ex
      printenv | sort
    displayName: Print env

  - bash: cake --bootstrap && cake --verbosity=$(Cake.Verbosity) --ispublisher=true
    displayName: Cake build
    env:
      TF_BUILD: true
