global using System;
global using System.Diagnostics.CodeAnalysis;
global using BoardGameGeek.Dungeon.Models;
global using FluentAssertions;
global using Microsoft.Extensions.Logging;
global using Serilog;
global using Serilog.Extensions.Logging;
global using Xunit;
global using Xunit.Abstractions;
