name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Docker:
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Docker login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cake build
      run: cake --bootstrap && cake --verbosity=verbose
