name: Build
on: [push, pull_request]

jobs:
  Docker:
    runs-on: ubuntu-16.04
    container: dockfool/cake-docker:latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Docker login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cake build
      run: cake --bootstrap && cake --verbosity=verbose
