name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Cache packages
        uses: actions/cache@v3.0.4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Docker login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Export runtime
        uses: crazy-max/ghaction-github-runtime@v2.0.0

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose --publish=true

      - name: Tests report
        if: always()
        uses: mikepenz/action-junit-report@v3.0.3
        with:
          check_name: tests
          fail_on_failure: true
          require_tests: true
          report_paths: "Artifacts/Tests/*/TestResults.xml"

      - name: Coverage report
        uses: 5monkeys/cobertura-action@v12
        with:
          minimum_coverage: 80
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          report_name: coverage
          show_class_names: true
          show_line: true
          show_branch: true
          skip_covered: false
          path: Artifacts/Tests/Coverage/Cobertura.xml
